name: pynes # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '3.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Awesome and entertaining mine game # 79 char long summary
description: |
  The object of the game is to clear an abstract minefield without detonating a mine.
  Very highly customizable and entertaining mine game.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: amd64
    run-on: all

apps:
  pynes:
    command: bin/pynes

parts:
  pynes:
    source: https://github.com/astraldev/pynes.git
    plugin: python
    command: desktop-launch $SNAP/usr/bin/org.astralco.pyne
    desktop: usr/share/applications/org.astralco.pyne.desktop
    requirements: ['requirements.txt']
    plugs: 
        - desktop

    stage-packages:
        - libcairo2
        - libgirepository1.0-1
        - gir1.2-gtk-4.0
        - python3-gi
        - libgtk-4-1
        - pkg-config
        - libcairo-gobject2
        - libcairo2
        - libfontconfig1
        - libfreetype6
        - libpixman-1-0